### ISSUE TITLE
1.12.2 forge-14.23.5.2838

### ISSUE THREAD

**Issue by bgencacat** [SteveKunG/SteveKunG-Lib#3]
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.3.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 8/11/19 3:06 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: stevekung/mods/stevekunglib/client/gui/GuiChatBase
	at stevekung.mods.ytchat.gui.GuiRightChatYT.func_146241_e(GuiRightChatYT.java:97)
	at net.minecraft.client.gui.GuiNewChat.func_146246_g(SourceFile:280)
	at net.minecraft.client.gui.GuiNewChat.func_146232_i(SourceFile:300)
	at net.minecraft.client.gui.GuiNewChat.func_146230_a(SourceFile:41)
	at stevekung.mods.ytchat.core.EventHandlerYT.onPreInfoRender(EventHandlerYT.java:129)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_20_EventHandlerYT_onPreInfoRender_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:717)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:173)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: stevekung.mods.stevekunglib.client.gui.GuiChatBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at stevekung.mods.ytchat.gui.GuiRightChatYT.func_146241_e(GuiRightChatYT.java:97)
	at net.minecraft.client.gui.GuiNewChat.func_146246_g(SourceFile:280)
	at net.minecraft.client.gui.GuiNewChat.func_146232_i(SourceFile:300)
	at net.minecraft.client.gui.GuiNewChat.func_146230_a(SourceFile:41)
	at stevekung.mods.ytchat.core.EventHandlerYT.onPreInfoRender(EventHandlerYT.java:129)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_20_EventHandlerYT_onPreInfoRender_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:717)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:173)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['bgencacat'/370, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['bgencacat'/370, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 966972920 bytes (922 MB) / 1375207424 bytes (1311 MB) up to 5495586816 bytes (5241 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5895m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version      | Source                           | Signature                                |
	|:------ |:--------------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2       | minecraft.jar                    | None                                     |
	| LCHIJA | mcp             | 9.42         | minecraft.jar                    | None                                     |
	| LCHIJA | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge           | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | stevekung's_lib | 1.1.3        | SteveKunG's-Lib-1.12.2-1.1.3.jar | b3468b224a74e296555ad7efeb35f482e6f445de |
	| LCHIJA | youtube_chat    | 1.4.1        | YouTubeChat-1.12.2-1.4.1.jar     | b3468b224a74e296555ad7efeb35f482e6f445de |

	Loaded coremods (and transformers): 
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.3.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.94' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: forge-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 416.94, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz`

**Comment by SteveKunG** [comment]
This is known YouTube Chat issue. I don't have time to fix this yet.
You should using SteveKunG's Lib 1.0.5 instead
