### ISSUE TITLE
No sound in game.

### ISSUE THREAD

**Issue by wkn311** [SteveKunG/SteveKunG-Lib#7]
When I downloaded the 1.15 version on the 1.12.2 update of SteveKunG's Lib, there is no sound at all in my game, can someone help?

**Comment by SteveKunG** [comment]
What???? Why install 1.15 mod on 1.12.2???

**Comment by wkn311** [comment]
No, 1.15 is the version of the mod itself, not the update

**Comment by wkn311** [comment]
Wait i mean 1.1.5

**Comment by SteveKunG** [comment]
OK, My library doesn't do anything with sound system.

**Comment by wkn311** [comment]
Well when I get rid of that mod and More Planets I can hear everything just fine, do you want me to list the mods that I have?

**Comment by SteveKunG** [comment]
You should provide log instead. Upload into pastebin or somewhere.

**Comment by wkn311** [comment]
[13:19:12] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:19:12] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:19:12] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[13:19:12] [main/INFO]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[13:19:12] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_251, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_251
[13:19:12] [main/WARN]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[13:19:12] [main/WARN]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[13:19:12] [main/INFO]: Searching C:\Users\Owner\AppData\Roaming\.technic\modpacks\something-fun-remastered\mods for mods
[13:19:12] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in GalaxySpace-1.12.2-2.0.13.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[13:19:12] [main/WARN]: The coremod galaxyspace.core.hooks.GSHooksLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:19:12] [main/WARN]: The coremod GSHooksLoader (galaxyspace.core.hooks.GSHooksLoader) is not signed!
[13:19:12] [main/WARN]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:19:12] [main/WARN]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
[13:19:12] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from More-Planets-1.12.2-2.1.12-GC251 (1).jar
[13:19:12] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_F5.jar
[13:19:12] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from SteveKunG's-Lib-1.12.2-1.1.5-deobf.jar
[13:19:12] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from SteveKunG's-Lib-1.12.2-1.1.5.jar
[13:19:12] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in themidnight-0.3.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[13:19:12] [main/WARN]: The coremod midnight (com.mushroom.midnight.core.MidnightLoadingPlugin) is not signed!
[13:19:12] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:19:12] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[13:19:12] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/Owner/AppData/Roaming/.technic/modpacks/something-fun-remastered/mods/More-Planets-1.12.2-2.1.12-GC251%20(1).jar Service=LaunchWrapper Env=CLIENT
[13:19:12] [main/DEBUG]: Instantiating coremod class SteveKunGLibPlugin
[13:19:12] [main/INFO]: Initializing SteveKunG's Lib plugin!
[13:19:12] [main/INFO]: Compatibility level set to JAVA_8
[13:19:12] [main/DEBUG]: The coremod stevekung.mods.stevekunglib.core.SteveKunGLibPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[13:19:12] [main/WARN]: The coremod SteveKunGLibPlugin (stevekung.mods.stevekunglib.core.SteveKunGLibPlugin) is not signed!
[13:19:12] [main/DEBUG]: Enqueued coremod SteveKunGLibPlugin
[13:19:12] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[13:19:12] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[13:19:12] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[13:19:12] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[13:19:12] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:19:12] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:19:12] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[13:19:12] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[13:19:12] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[13:19:12] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[13:19:12] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: C:\Users\Owner\AppData\Roaming\.technic\modpacks\something-fun-remastered\mods\OptiFine_1.12.2_HD_U_F5.jar
[13:19:12] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:19:12] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[13:19:12] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[13:19:12] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[13:19:12] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[13:19:12] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[13:19:12] [main/DEBUG]: Injection complete
[13:19:12] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[13:19:12] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[13:19:14] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[13:19:14] [main/ERROR]: FML appears to be missing any signature data. This is not a good thing
[13:19:14] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[13:19:14] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:19:14] [main/DEBUG]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[13:19:14] [main/DEBUG]: Injection complete
[13:19:14] [main/DEBUG]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[13:19:14] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[13:19:14] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[13:19:14] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:19:14] [main/DEBUG]: Injecting coremod GSHooksLoader \{galaxyspace.core.hooks.GSHooksLoader\} class transformers
[13:19:14] [main/TRACE]: Registering transformer galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
[13:19:14] [main/INFO]: [galaxyspace.core.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Parsing hooks container galaxyspace.core.hooklib.minecraft.SecondaryTransformerHook
[13:19:14] [main/INFO]: [HOOKLIB]  Obfuscated: true
[13:19:14] [main/DEBUG]: Injection complete
[13:19:14] [main/DEBUG]: Running coremod plugin for GSHooksLoader \{galaxyspace.core.hooks.GSHooksLoader\}
[13:19:14] [main/DEBUG]: Running coremod plugin GSHooksLoader
[13:19:14] [main/INFO]: [galaxyspace.core.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Parsing hooks container galaxyspace.core.hooks.GSHooksManager
[13:19:14] [main/DEBUG]: Coremod plugin class GSHooksLoader run successfully
[13:19:14] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:19:14] [main/DEBUG]: Injecting coremod MicdoodlePlugin \{micdoodle8.mods.miccore.MicdoodlePlugin\} class transformers
[13:19:14] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:99]: Successfully Registered Transformer
[13:19:14] [main/TRACE]: Registering transformer micdoodle8.mods.miccore.MicdoodleTransformer
[13:19:14] [main/DEBUG]: Injection complete
[13:19:14] [main/DEBUG]: Running coremod plugin for MicdoodlePlugin \{micdoodle8.mods.miccore.MicdoodlePlugin\}
[13:19:14] [main/DEBUG]: Running coremod plugin MicdoodlePlugin
[13:19:15] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:292]: [Micdoodle8Core]: Patching game...
[13:19:15] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:292]: [Micdoodle8Core]: Patching game...
[13:19:15] [main/DEBUG]: Coremod plugin class MicdoodlePlugin run successfully
[13:19:15] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[13:19:15] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@4d065e1a
[13:19:15] [main/DEBUG]: Injecting coremod SteveKunGLibPlugin \{stevekung.mods.stevekunglib.core.SteveKunGLibPlugin\} class transformers
[13:19:15] [main/DEBUG]: Injection complete
[13:19:15] [main/DEBUG]: Running coremod plugin for SteveKunGLibPlugin \{stevekung.mods.stevekunglib.core.SteveKunGLibPlugin\}
[13:19:15] [main/DEBUG]: Running coremod plugin SteveKunGLibPlugin
[13:19:15] [main/DEBUG]: Coremod plugin class SteveKunGLibPlugin run successfully
[13:19:15] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[13:19:15] [main/DEBUG]: Validating minecraft
[13:19:15] [main/INFO]: [galaxyspace.core.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Injecting hooks into class net.minecraftforge.fml.common.Loader
[13:19:15] [main/INFO]: [galaxyspace.core.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Patching method net.minecraftforge.fml.common.Loader#injectData([Ljava/lang/Object;)
[13:19:15] [main/INFO]: [galaxyspace.core.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Methods dictionary loaded in 4 ms
[13:19:15] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:19:15] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[13:19:15] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[13:19:15] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[13:19:15] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[13:19:15] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[13:19:15] [main/INFO]: [galaxyspace.core.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Injecting hooks into class net.minecraft.world.World
[13:19:15] [main/INFO]: [galaxyspace.core.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Patching method net.minecraft.world.World#setBlockState(Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;I)
[13:19:16] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[13:19:16] [main/INFO]: [galaxyspace.core.hooklib.asm.HookLogger$SystemOutLogger:debug:20]: [DEBUG] Injecting hooks into class net.minecraft.world.World
[13:19:16] [main/FATAL]: Mixin apply failed mixins.stevekung's_lib.json:WorldMixin -> net.minecraft.world.World: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method getBlockState in mixins.stevekung's_lib.json:WorldMixin was not located in the target class net.minecraft.world.World. Using refmap mixins.stevekung's_lib.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method getBlockState in mixins.stevekung's_lib.json:WorldMixin was not located in the target class net.minecraft.world.World. Using refmap mixins.stevekung's_lib.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:387) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:360) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:293) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:261) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) [More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) [More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) [More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_251]
	at net.minecraft.client.main.Main.main(SourceFile:38) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.stevekung's_lib.json:WorldMixin] from phase [DEFAULT] in config [mixins.stevekung's_lib.json] FAILED during APPLY
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.main.Main.main(SourceFile:38)
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[13:19:16] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[13:19:16] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method getBlockState in mixins.stevekung's_lib.json:WorldMixin was not located in the target class net.minecraft.world.World. Using refmap mixins.stevekung's_lib.refmap.json
[13:19:16] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:387)
[13:19:16] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:360)
[13:19:16] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:293)
[13:19:16] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:261)
[13:19:16] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
[13:19:16] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
[13:19:16] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267)
[13:19:16] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
[13:19:16] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
[13:19:16] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
[13:19:16] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
[13:19:16] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 12 more
[13:19:16] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.stevekung's_lib.json:WorldMixin] from phase [DEFAULT] in config [mixins.stevekung's_lib.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method getBlockState in mixins.stevekung's_lib.json:WorldMixin was not located in the target class net.minecraft.world.World. Using refmap mixins.stevekung's_lib.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:387) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:360) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:293) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:261) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[More-Planets-1.12.2-2.1.12-GC251%20(1).jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
[13:19:16] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[13:19:16] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[13:19:16] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[13:19:16] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[13:19:16] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[13:19:16] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[13:19:16] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by wkn311** [comment]
Is this it?

**Comment by SteveKunG** [comment]
BTW, it's not sound issue. It is mixin. I'm gonna do it on my side.

**Comment by wkn311** [comment]
What does that mean? Sorry if I sound rude

**Comment by SteveKunG** [comment]
For simple it's a bug.
So please try with this file
https://www.dropbox.com/s/rlr4ykfm0tnvyrs/SteveKunG%27s-Lib-1.12.2-1.1.5.jar?dl=1

**Comment by wkn311** [comment]
Hmm, still dont hear anything.

**Comment by SteveKunG** [comment]
Then it's other mods issue, Also any additional full log?

**Comment by wkn311** [comment]
Theres another log file but it looks like complete gibberish

**Comment by wkn311** [comment]
Its called 2020-05-27-1.log.gz

**Comment by wkn311** [comment]
Or do you want me to show you the log that I used before, it might be updated to the mod that you sent me.

**Comment by SteveKunG** [comment]
Yes sure but upload it to pastebin or hastebin

**Comment by wkn311** [comment]
ok here you go

https://pastebin.com/CLnysuNr

**Comment by SteveKunG** [comment]
![image](https://user-images.githubusercontent.com/6128413/83067523-04d52100-a091-11ea-834e-b1dfcb064c9e.png)
Found a problem. More detail at : https://bugs.mojang.com/browse/MC-9974

**Comment by wkn311** [comment]
Wow, all I had to do was press F3 and T, thanks dude your the best.

**Comment by wkn311** [comment]
That fix saved me from starting from scratch on my modpack!

**Comment by SteveKunG** [comment]
No problem, you bring a new issue that I haven't found it.
Also published new version on curseforge

**Comment by wkn311** [comment]
Thanks!
